.gitignore, README.md, cassette.go, examples/example1.go, examples/example2.go, examples/main.go, govcr.go, govcr_test.go
The httptest solution proved to be limited with 'https' as the Proxy in http.Client does not support 'https'
=> [init2] http.Client based solution

README.md, cassette.go, examples/example3.go, examples/main.go, govcr.go, govcr_test.go
A separate PR will see the implementation of RequestHeaderFilter and RequestBodyFilter
=> [REQ-MATCH] Improve request matching

.gitignore, Makefile, cassette.go, govcr.go, govcr_test.go
This introduces the use of hooks to exclude selected headers or amend the Body during request match comparison
=> [Hooks-2] First implementation of hooks

examples/example2.go, examples/example3.go, govcr.go, govcr_test.go
Add support for client configuration and custom filter functions
=> [BugFix-ClientParams] Add support for client configuration

govcr.go
true and false seem to have been flipped
=> correction to comment for ExcludeHeaderFunc

cassette.go, govcr.go, request.go, response.go
See issue #37 for further information
=> Remove serialisation of Path in the cassette

request.go, request_test.go, response.go, response_test.go
This change should be backwards compatible.
=> Allow multiple filter cases

.golangci.yml, README.md, cassette/cassette.go, cassette/track/http.go, cassette/track/mutator_test.go, cassette/track/track.go, govcr.go, matchers.go, pcb.go, vcrtransport.go
Added NewBlankRequestMatcher
Renamed NewDefaultRequestMatcher to NewStrictRequestMatcher
README updates
Added Test_Mutator_Multiple_On
=> Updates to RequestMutator

Makefile, cassette/track/http.go, controlpanel.go, govcr_wb_test.go, pcb.go, vcrtransport.go
Improved + expanded GoVCRWBTestSuite
Added AddRecordingMutators
Linting
=> Improve handling of HTTP trailers

cassette/cassette.go, cassette/cassette_wb_test.go, govcr_test.go, govcr_wb_test.go, pcb.go
=> Refined TestRoundTrip_RequestMatcherDoesNotMutateState

cassette/cassette.go, cassette/cassette_wb_test.go, govcr_test.go, govcr_wb_test.go, pcb.go, pcb_wb_test.go
=> Immutability test part2

Makefile, cassette/track/http.go, cassette/track/http_test.go, cassette/track/mutator.go, cassette/track/mutator_test.go, cassette/track/track.go
=> Few bug fixes + additional unit tests

cassette/cassette.go, cassette/cassette_test.go, cassette/track/http_wb_test.go, controlpanel_wb_test.go, govcr_test.go, vcrsettings.go, vcrsettings_wb_test.go
=> Enable switching a decrypted cassette to encryption mode

README.md
=> docs: Fix README references to defunct WithCassette()

.golangci.yml, README.md, cassette/cassette.go, cassette/cassette_test.go, cassette/cassette_wb_test.go, cassette/track/http_test.go, cassette/track/mutator_test.go, cassette/track/track.go, cmd/govcr/main.go, concurrency_test.go, controlpanel.go, controlpanel_wb_test.go, encryption/.study/rsa.go, encryption/aesgcm.go, encryption/aesgcm_test.go, encryption/chacha20poly1305_test.go, examples/Example1_test.go, examples/Example2_test.go, examples/Example3_test.go, examples/Example4_test.go, go.mod, govcr.go, govcr_test.go, govcr_wb_test.go, matchers.go, matchers_test.go, pcb.go, pcb_wb_test.go, vcrsettings.go, vcrtransport.go
=> BREAKING CHANGE: rename CassetteMaker, WithCassetteCrypto*, WithCassetteCrypter*

cassette/track/track.go
=> fix: invalid hydration of Response.Request.Body

cassette/track/track.go, cassette/track/track_test.go
=> test: add test for Track ToHTTPResponse

cassette/cassette.go, cassette/track/http.go, cassette/track/track.go, cassette/track/track_test.go, encryption/aesgcm.go, encryption/chacha20poly1305.go, encryption/nonce.go, encryption/nonce_wb_test.go, pcb.go
=> Remove RequestMatcher TODO

.gitattributes
=> chore: add .gitattributes rule to reduce PR diffs

cassette/track/http.go
=> docs: clarified comment on Response.Request
